# config.ini
[ui]
# Адресс сайта
bas_url = https://shop.mts.ru
# Время ожидания
timeout = 6
# Название браузера для тестирования: Google Chrome "chrom" или Firefox "ff"
browser_name = chrom1

[api]
bas_url_v1 = https://shop.mts.ru/api/
bas_url_v2 = https://shop.mts.ru/apigw/api/